name: Go

on: workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
    - name: Build
      run: go build -v ./...
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.0.10
      with:
        name: my-artifact    
    - name: Display structure of downloaded files
        run: ls -R
